succ(s,[b,c,d]).
succ(b,[c,e]).
succ(d,[f]).
succ(e,[k,h]).
succ(f,[h]).
succ(k,[i]).
succ(h,[g]).
succ(i,[h,j]).
succ(j,[g]).

heuristic(s,g,8).
heuristic(b,g,7).
heuristic(c,g,8).
heuristic(d,g,5).
heuristic(e,g,4).
heuristic(f,g,3).
heuristic(h,g,2).
heuristic(k,g,3).
heuristic(i,g,2).
heuristic(j,g,1).
heuristic(g,g,0).

leng(s,d,3).
leng(s,b,2).
leng(s,c,2).
leng(b,c,2).
leng(b,e,2).
leng(d,f,2).
leng(e,h,2).
leng(e,k,1).
leng(f,h,1).
leng(h,g,2).
leng(k,i,1).
leng(i,h,1).
leng(i,j,1).
leng(j,g,1).
